version: '3'
volumes:
  wordpress:
  db:
services:
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_soukatsu
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/createactouc
      - ./dev-resources/wordpress/plugins:/var/www/html/wp-content/plugins
      - ./dev-resources/wordpress/languages:/var/www/html/wp-content/languages
      - ./dev-resources/wordpress/wp-config.php:/var/www/html/wp-config.php
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: wp_user
      PMA_PASSWORD: wp_password
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp_soukatsu
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      - ./dev-resources/db:/docker-entrypoint-initdb.d
